services:
  - type: web
    name: sporttimes
    runtime: node
    plan: starter
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    healthCheckPath: /
